language: rust
rust:
  - stable
  - nightly
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench --verbose; fi
  - cargo doc --verbose --no-deps